### PR TITLE
improve: @roots/bud-server

### PR DESCRIPTION
**Pull request by kellymears**
## Overview

- adds SSL support
- if specified dev port is busy a new port is allocated instead
- maps middleware types to keys
- typings mandate that async hooks be called with `.async` and sync with `.on`
- typings mandate that async filters be called with `.filterAsync` and sync with `.filter`
- adds `hooks.fire` (events: always passed `bud`, always `async`)
- adds `hooks.action` (callbacks for `hooks.fire`)

```ts
bud.hooks.action('some-action', async (app) => app.log('did some action'))
await bud.hooks.fire('some-action')
```

this is better than trying to remember to continue passing `bud` in a waterfall hook (if you forget to do it and a function later on assumes it's set... RIP).

### removes all `server.` values from `bud.store`

This removes all of the server stuff from `bud.store`. because those values are very likely to be overwritten late and it's potentially misleading -- if someone finds the store they're gonna be super confused. 

`bud.hooks` is working really well and very predictably these days. i think we should deprecate `bud.store soon`. it's just state we carry around and fight with for no reason other than inertia. i like that `bud.hooks` is:

1. made up of functions
2. idempotent by nature

refers: none
closes: none

## Type of change

- MINOR: Backwards compatible feature

### CODE REVIEW

**Comment by swalkinshaw** [comment]
What would the end result/config look like to get an HTTPS proxy working in sage/bud with this now?

Got some conflicts to fix too

**Comment by kellymears** [comment]
I'm reverting this to draft for a minute. It's a big change and it's frustrated me a couple times.

If #1096 ends up getting merged then I know something is wack here because getting those two changes to play nice has been a bit of a struggle. #1096 is big but it's presentational. this is a deep change and touches a lot of the codebase.

> What would the end result/config look like to get an HTTPS proxy working in sage/bud with this now?

This change would make it easy to configure most any option value in the proxy setup with a hook. I think we can do a similar thing in a way that has less broad implications.

The more scoped end goal is to open up the [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware) options so people who know more than me about how this _should_ work can configure it from outside the repo. those settings can be potentially used as defaults.

For now I want to leave this as a draft so I can hopefully pilfer the best bits in smaller ways.

**Comment by kellymears** [comment]
@swalkinshaw actually, look at this again, and this is is doable from within a bud configuration file right now:

https://github.com/roots/bud/issues/934#issuecomment-1030357236

**Comment by kellymears** [comment]
both of the failed tests so far have been the result of me completely separating async/sync hooks. so, these are problems on `main` as well, it's just tha the stricter typings in this PR are forcing the issue (which is what i wanted).

i'll have time to finish fixing them up later on today or tomorrow.

**Comment by kellymears** [comment]
increased test coverage significantly 👐

**Review by retlehs — APPROVED** [review]

**Pull request merged**
