### PR TITLE
:hammer: dev(none): 5.8.0 release

### PR DESCRIPTION
**Pull request by kellymears**
## changelog

https://github.com/roots/bud/compare/v5.7.7...main

- #1303
- #1315
- #1327
- #1328
- #1335
- #1341

## contrib

- @kellymears 
- @alwaysblank 
- @joshuafredrickson 
- @retlehs

### CODE REVIEW

**Comment by robrecord** [comment]
`1337 ;-)`

**Comment by kellymears** [comment]
@retlehs i'm finishing up the release post. let me know if i'm good otherwise.

**Review by retlehs — APPROVED** [review]

**Comment by kellymears** [comment]
@retlehs the only thing i changed was applying the `@once` decorator to the `openBrowser`  method in the `Notifier` class. Pretty annoying to have it open the browser on every compilation 😳

**Comment by robrecord** [comment]
🎉

**Pull request merged**
